# Generated by Django 4.1.2 on 2022-11-18 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("testapp", "0003_alter_course_description_test_quetion_answer"),
    ]

    operations = [
        migrations.CreateModel(
            name="Submition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("submited", models.BooleanField(default=False)),
                ("points", models.DecimalField(decimal_places=0, max_digits=10)),
                ("answers", models.ManyToManyField(to="testapp.answer")),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="testapp.student",
                    ),
                ),
                (
                    "test",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="testapp.test"
                    ),
                ),
            ],
        ),
    ]
