# Generated by Django 4.1.2 on 2023-01-10 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0006_alter_test_time_to_publish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='time_to_submit',
            field=models.DurationField(),
        ),
    ]
